version: "3"
services:
  url-scraper:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      PORT: 80
      NODE_ENV: dev # to test production builds disable this.
      # NODE_ENV: production # to test production builds enable this.
      SQL_DB_USERNAME: $SQL_DB_USERNAME
      SQL_DB_PASSWORD: $SQL_DB_PASSWORD
      SQL_DB_HOST: mysqldb
      SQL_DB_NAME: $SQL_DB_NAME

    ports:
      - 80:80
    volumes:
      - url-scraper-node-modules-volume:/app/node_modules
      - ./src:/app/src
    deploy:
      replicas: 1
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$SQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$SQL_DB_NAME
      - MYSQL_USER=$SQL_DB_USERNAME
      - MYSQL_PASSWORD=$SQL_DB_PASSWORD
    ports:
      - $SQL_DB_LOCAL_PORT:$SQL_DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
volumes:
  url-scraper-node-modules-volume:
  db:
